package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import beans.*;
import java.sql.Connection;
import special.*;

public final class adminrecreply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(4);
    _jspx_dependants.add("/admin/adminheader.jsp");
    _jspx_dependants.add("/admin/adminleftside.jsp");
    _jspx_dependants.add("/admin/adminmiddlemenu.jsp");
    _jspx_dependants.add("/admin/adminrightside.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write(".style1 {font-family: Verdana, Arial, Helvetica, sans-serif}\r\n");
      out.write("\r\n");
      out.write(".admintext\r\n");
      out.write("{\r\n");
      out.write("font-size:44px;\r\n");
      out.write("color:#3E3EFF;\r\n");
      out.write("}\r\n");
      out.write(".sidelinks{text-decoration:none;color:#FFFFFF}\r\n");
      out.write(".gnduasr\r\n");
      out.write("{\r\n");
      out.write("font-size:24px;\r\n");
      out.write("color:#3E3EFF;\r\n");
      out.write("}\r\n");
      out.write(".logobg\r\n");
      out.write("{\r\n");
      out.write("background-color:#090909\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.links{text-decoration: none;font-size: 17px}\r\n");
      out.write("a.links:hover{text-decoration: none;color:blue;font-size: 19px;color:olive;}\r\n");
      out.write("\r\n");
      out.write(".eportal \r\n");
      out.write("{\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\ttop:30px;\r\n");
      out.write("\tleft:1148px;\r\n");
      out.write("\tcolor: 3E3EFF;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tz-index:19;\r\n");
      out.write("\twidth: 66px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".botgndu{\r\n");
      out.write("color:#3E3EFF\r\n");
      out.write("}\r\n");
      out.write(".drop1\r\n");
      out.write("{display:none}\r\n");
      out.write(".drop2\r\n");
      out.write("{display:inline}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function collapse(m)\r\n");
      out.write("{\r\n");
      out.write("if(m!=\"a1\")\r\n");
      out.write("document.getElementById(\"a1\").className=\"drop1\";\r\n");
      out.write("if(m!=\"a2\")\r\n");
      out.write("document.getElementById(\"a2\").className=\"drop1\";\r\n");
      out.write("if(m!=\"a3\")\r\n");
      out.write("document.getElementById(\"a3\").className=\"drop1\";\r\n");
      out.write("}\r\n");
      out.write("function f(n)\r\n");
      out.write("{\r\n");
      out.write("collapse(n);\r\n");
      out.write("var p= document.getElementById(n);\r\n");
      out.write("if(p.className==\"drop1\")\r\n");
      out.write("p.className=\"drop2\";\r\n");
      out.write("else\r\n");
      out.write("p.className=\"drop1\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"866\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    ");
      out.write("<td height=\"110\"><table width=\"100%\" height=\"179\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"179\" height=\"179\" bgcolor=\"#C1C1FF\" class=\"logobg\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"logo_p.jpg\" width=\"137\" height=\"129\" /></td>\r\n");
      out.write("        <td width=\"1033\" background=\"slide4.jpg\"  bgcolor=\"#CCCCFF\">\r\n");
      out.write("\t\t<p align=\"center\" class=\"admintext\">Welcome Administrator<br><marquee class=\"gnduasr\">GNDU,AMRITSAR</marquee></p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p align=\"right\"><span class=\"eportal\">E-Portal</span></p>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          <a href=\"#\"></a></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"36\"><table width=\"100%\" height=\"34\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"181\" height=\"34\" bgcolor=\"#E4CAFF\"><span class=\"style1\">GNDU PORTAL </span></td>\r\n");
      out.write("        <td width=\"817\" bgcolor=\"#E4CAFF\"><table width=\"345\" height=\"30\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("           \r\n");
      out.write("         <td width=\"59\" class=\"search\">&nbsp;Search</td>\r\n");
      out.write("          \r\n");
      out.write("            <td width=\"282\"><table width=\"286\" height=\"30\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("\t\t\t  <form name=\"f1\" action=\"adminsearch.jsp\">\r\n");
      out.write("                <td width=\"253\"><input type=\"text\" name=\"search\" size=\"42\" /></td>\r\n");
      out.write("               <td width=\"29\"><input type=\"submit\" value=\"search\" /></td>\r\n");
      out.write("              </form>\r\n");
      out.write("\t\t\t </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("        <td width=\"212\" align=\"right\" bgcolor=\"#E4CAFF\"><a href=\"adminlogout.jsp\" class=\"logout\">LogOut</a></td>\r\n");
      out.write("        ");

		String adminname=(String)session.getAttribute("admin");
		String image=(String)session.getAttribute("im");
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>");
      out.write("\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr bgcolor=\"#2B1521\">\r\n");
      out.write("    <td height=\"617\" valign=\"top\"><table width=\"100%\" height=\"615\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("     \r\n");
      out.write("      <tr bgcolor=\"#FFB0FF\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("        <td width=\"178\" height=\"613\" valign=\"top\" bgcolor=\"#E4CAFF\">\r\n");
      out.write("\t\t<table width=\"100%\" height=\"151\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t  <td width=\"174\" height=\"96\" valign=\"top\" bgcolor=\"#2B1521\">\r\n");
      out.write("\t\t<table width=\"100%\" height=\"113\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"88\" height=\"113\"><a href=\"admin.jsp\"><img src=\"../images/");
      out.print(image);
      out.write("\" width=\"88\" height=\"96\" /></a></td>\r\n");
      out.write("          \t<td width=\"89\" align=\"center\"><span class=\"sidelinks\">");
      out.print(adminname);
      out.write("</span></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t </table>         </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t  <td height=\"27\" align=\"center\" bgcolor=\"#E4CAFF\"><a href=\"javascript:f('a1')\">Manage Students</a>\r\n");
      out.write("\t\t  <br>\r\n");
      out.write("\t\t    <table width=\"200\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"drop1\" id=\"a1\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"addstudent.jsp\" target=\"_self\">Add Student</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"modifystudent1.jsp\" target=\"_self\">Modify Student</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"deletestudent1.jsp\" target=\"_self\">Delete Student</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t  <td height=\"27\" align=\"center\" bgcolor=\"#E4CAFF\"><a href=\"javascript:f('a2')\">Manage Teachers</a>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t    <table width=\"200\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"drop1\" id=\"a2\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"addteacher.jsp\" target=\"_self\">Add Teacher</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"modifyteacher1.jsp\" target=\"_self\">Modify Teacher</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"deleteteacher1.jsp\" target=\"_self\">Delete Teacher</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t  <td height=\"27\" align=\"center\" bgcolor=\"#E4CAFF\"><a href=\"javascript:f('a3')\">Manage Groups</a>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t    <table width=\"200\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"drop1\" id=\"a3\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"creategroup.jsp\" target=\"_self\">Create Group</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"adminshowgroups.jsp\" target=\"_self\">Delete Group</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td align=\"center\"><a class=\"links\" href=\"adminshowgroups.jsp\" target=\"_self\">Show Groups</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  ");
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t </table>\t\t  </td>\r\n");
      out.write("\t\t  \r\n");
      out.write("        <td width=\"846\" height=\"613\" align=\"right\" valign=\"top\" bgcolor=\"#FFFFF\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            ");
      out.write("<td height=\"22\" align=\"center\" bgcolor=\"#FFFFFF\"><a href=\"adminnews.jsp\" class=\"centerlinks\">News</a></td>\r\n");
      out.write("            <td align=\"center\" bgcolor=\"#FFFFFF\"><a href=\"allprofiles.jsp\" class=\"centerlinks\">Profiles</a></td>\r\n");
      out.write("            <td align=\"center\" bgcolor=\"#FFFFFF\"><a href=\"#\" class=\"centerlinks\">E-Mail</a></td>\r\n");
      out.write("            <td align=\"center\" bgcolor=\"#FFFFFF\"><a href=\"#\" class=\"centerlinks\">Discussion</a></td>\r\n");
      out.write("            <td align=\"center\" bgcolor=\"#FFFFFF\"><a href=\"adminalbums.jsp\" class=\"centerlinks\">Albums</a></td>");
      out.write("\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("              <table width=\"100%\" height=\"591\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td bgcolor=\"#FFFFF\" valign=\"top\" align=\"center\">\r\n");
      out.write("                  \r\n");
      out.write("                    <table width=\"100%\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          ");

		 String groupname=(String)session.getAttribute("groupname");
		  String topicname=(String)session.getAttribute("topicname");
		  String sgroupid=(String)session.getAttribute("groupid");
		  String stopicid=(String)session.getAttribute("topicid");
		  
		  
		  
      out.write("\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("            <td width=\"50%\" align=\"center\">Group Name : <a href=\"admingrouptopics.jsp?groupid=");
      out.print(sgroupid );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(groupname);
      out.write("</a></td>\r\n");
      out.write("            <td width=\"50%\" align=\"center\">Topic : <a href=\"admintopiccontent.jsp?topicid=");
      out.print(stopicid );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(topicname );
      out.write("</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table> \r\n");
      out.write("       \r\n");
      out.write("                \r\n");
      out.write("                  ");

				  
				 int tmsgid=Integer.parseInt(request.getParameter("tmsgid"));
                 int topicid=Integer.parseInt(request.getParameter("topicid"));
                  bean b1=new bean();
				b1.setTmsgid(tmsgid);
				
					b1.showreplies();		 
				
				String comm1=b1.getCommentor();
				
				bean b5=new bean();
						b5.setImgusername(comm1);
						String c1image=b5.cimage();
						
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br><br><br><br>\t\r\n");
      out.write("\t\t\t<table width='600' height='143' border='1' cellpadding='0' cellspacing='0'>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("<td width=\"129\" height=\"113\" align=\"center\"><table width=\"103\" height=\"141\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"93\"><img src=\"../images/");
      out.print(c1image);
      out.write("\" alt=\"a\" width=\"94\" height=77 /></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"40\" align=\"center\">");
      out.print(comm1 );
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table></td>\r\n");
      out.write("<td width=\"479\"><table width=\"100%\" height=\"145\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"center\" width=\"80%\">Commented By : ");
      out.print(b1.getCommentor() );
      out.write("</td>\r\n");
      out.write("  <td align=\"right\">");
      out.print(b1.getTime() );
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"center\">");
      out.print(b1.getTcomment() );
      out.write("</td>\r\n");
      out.write("   <td align=\"center\">&nbsp;</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    \r\n");
      out.write("    <td>&nbsp;</td>\r\n");
      out.write("    <td height=\"57\" align=\"right\">");
      out.print(b1.getDat() );
      out.write("</td>\r\n");
      out.write("    \r\n");
      out.write("  </tr>\r\n");
      out.write("</table></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\t\t\t\r\n");
      out.write("\t\t\t");
 	
				
				bean b3=new bean();
				b3.setReplyid(tmsgid);	
				ArrayList a=b3.showreplies1();
				
				Iterator t=a.iterator();
				Connection con=Dataconnection.conestablished();	 				  
				while(t.hasNext())
				{
					 bean b2=(bean)t.next();
					String comm=b2.getCommentor();
					int rectmsgid=b2.getTmsgid();	
						bean b4=new bean();
						b4.setImgusername(comm);
						String cimage=b4.cimage1(con);
						b4.setReplyid(rectmsgid);
						int num=b4.numofreplies1(con);
				
      out.write("\r\n");
      out.write("\t\t\t<table width='600' height='75' border='1' cellpadding='0' cellspacing='0'>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("<td width=\"80\" height=\"40\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td><img src=\"../images/");
      out.print(cimage);
      out.write("\" width=\"60\" height=45\" /></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=\"center\">");
      out.print(comm );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\t<td width=\"479\"><table width=\"514\" height=\"15\" border='0' cellpadding='0' cellspacing='0'>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td width=\"85%\" align=\"center\">");
      out.print(b2.getTcomment() );
      out.write("</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<table border=\"0\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>");
      out.print(b2.getTime() );
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write(" <td>");
      out.print(b2.getDat() );
      out.write("</td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr><td><a href=\"adminrecreply.jsp?tmsgid=");
      out.print(b2.getTmsgid() );
      out.write("&topicid=");
      out.print(topicid );
      out.write("\">reply(");
      out.print(num );
      out.write(")</a></td></tr>\r\n");
      out.write(" \r\n");
      out.write(" </table>\r\n");
      out.write(" </td>\r\n");
      out.write(" \r\n");
      out.write(" </tr>\r\n");
      out.write(" \r\n");
      out.write(" </table>\r\n");
      out.write(" </table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

 		}con.close();
      out.write("\r\n");
      out.write(" \t\t\r\n");
      out.write("\t\t\t\t<table width='600' height='60' border='1' cellpadding='0' cellspacing='0'>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<form name=\"t1\" action=\"adminrecreply1.jsp\">\r\n");
      out.write("\t\r\n");
      out.write("\t<td width=\"80\" height=\"40\" align=\"center\"><img src=\"images/");
      out.print(image);
      out.write("\" width=\"60\" height=40\" /></td>\r\n");
      out.write("\t<td width=\"479\"><table width=\"514\" height=\"15\" border='0' cellpadding='0' cellspacing='0'>\r\n");
      out.write("\t<tr><td width=\"85%\"><textarea name=\"comment\" cols=\"50\"></textarea></td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<input type=\"hidden\" name=\"tmsgid\" value=");
      out.print(tmsgid );
      out.write(">\r\n");
      out.write("\t<input type=\"hidden\" name=\"topicid\" value=");
      out.print(topicid );
      out.write(">\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"submit\" value=\"Comment\">\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</td>\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t </table>\t\t\r\n");
      out.write(" \t\t\r\n");
      out.write("                \r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("          </table></td>\r\n");
      out.write("        <td width=\"175\" valign=\"top\" bgcolor=\"#E4CAFF\"><table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            ");
      out.write("<td bgcolor=\"#2B1521\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td align=\"center\" bgcolor=\"#E4CAFF\"><a href=\"#\">Info About Course </a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td align=\"center\" bgcolor=\"#E4CAFF\"><a href=\"#\">Events</a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td align=\"center\" bgcolor=\"#E4CAFF\"><a href=\"#\">Recent Activity </a></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td bgcolor=\"#E4CAFF\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td bgcolor=\"#E4CAFF\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td bgcolor=\"#E4CAFF\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td bgcolor=\"#E4CAFF\">&nbsp;</td>");
      out.write("\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"30\" align=\"center\" bgcolor=\"#E4CAFF\" class=\"botgndu\">Guru Nank Dev University </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
